import type { InfiniteTableColumn } from '@infinite-table/infinite-react';

export interface WebFramework {
  id: number;
  name: string;
  created_at: string;
  stargazers_count: number;
  language: string;
  license: string;
  has_wiki: boolean;
  week_issue_change: number;
}

export interface WebFrameworkDetailed extends WebFramework {
  full_name: string;
  description: string;
  license: string;
  html_url: string;
  pushed_at: string;
  updated_at: string;
  homepage: string;
  open_issues_count: number;
  forks_count: number;
  has_pages: boolean;
  has_projects: boolean;
  subscribers_count: number;
  closed_issues_count: number;
  open_pr_count: number;
  closed_pr_count: number;
  topics: string[];
  stats: number[];
}

export const columns: Record<string, InfiniteTableColumn<WebFramework>> = {
  id: {
    field: 'id',
  },
  name: {
    field: 'name',
  },
  created_at: {
    field: 'created_at',
  },
  stargazers_count: {
    field: 'stargazers_count',
  },
  language: {
    field: 'language',
  },
  has_wiki: {
    field: 'has_wiki',
  },
  week_issue_change: {
    field: 'week_issue_change',
  },
};

export const data: WebFrameworkDetailed[] = [
  {
    id: 10270250,
    name: 'react',
    full_name: 'facebook/react',
    html_url: 'https://github.com/facebook/react',
    description:
      'A declarative, efficient, and flexible JavaScript library for building user interfaces.',
    created_at: 'Fri May 24 2013',
    updated_at: 'Mon Dec 20 2021',
    pushed_at: 'Sun Dec 19 2021',
    homepage: 'https://reactjs.org',
    stargazers_count: 179429,
    language: 'JavaScript',
    forks_count: 36403,
    open_issues_count: 920,
    license: 'MIT License',
    topics: ['declarative', 'frontend', 'javascript', 'library', 'react', 'ui'],
    subscribers_count: 6671,
    has_projects: true,
    has_wiki: true,
    has_pages: true,
    closed_issues_count: 10326,
    open_pr_count: 249,
    closed_pr_count: 11408,
    week_issue_change: 5,
    stats: [179429, 36403, 920, 6671, 249],
  },
  {
    id: 24195339,
    name: 'angular',
    full_name: 'angular/angular',
    html_url: 'https://github.com/angular/angular',
    description: 'The modern web developer’s platform',
    created_at: 'Thu Sep 18 2014',
    updated_at: 'Mon Dec 20 2021',
    pushed_at: 'Sun Dec 19 2021',
    homepage: 'https://angular.io',
    stargazers_count: 78348,
    language: 'TypeScript',
    forks_count: 20569,
    open_issues_count: 1889,
    license: 'MIT License',
    topics: [
      'angular',
      'javascript',
      'pwa',
      'typescript',
      'web',
      'web-framework',
      'web-performance',
    ],
    subscribers_count: 3119,
    has_projects: true,
    has_wiki: false,
    has_pages: false,
    closed_issues_count: 21706,
    open_pr_count: 159,
    closed_pr_count: 20052,
    week_issue_change: 12,
    stats: [78348, 20569, 1889, 3119, 159],
  },
  {
    id: 11730342,
    name: 'vue',
    full_name: 'vuejs/vue',
    html_url: 'https://github.com/vuejs/vue',
    description:
      '🖖 Vue.js is a progressive, incrementally-adoptable JavaScript framework for building UI on the web.',
    created_at: 'Mon Jul 29 2013',
    updated_at: 'Mon Dec 20 2021',
    pushed_at: 'Mon Dec 20 2021',
    homepage: 'http://vuejs.org',
    stargazers_count: 191435,
    language: 'JavaScript',
    forks_count: 30945,
    open_issues_count: 546,
    license: 'MIT License',
    topics: ['framework', 'frontend', 'javascript', 'vue'],
    subscribers_count: 6187,
    has_projects: true,
    has_wiki: true,
    has_pages: false,
    closed_issues_count: 9318,
    open_pr_count: 224,
    closed_pr_count: 1878,
    week_issue_change: -9,
    stats: [191435, 30945, 546, 6187, 224],
  },
  {
    id: 74293321,
    name: 'svelte',
    full_name: 'sveltejs/svelte',
    html_url: 'https://github.com/sveltejs/svelte',
    description: 'Cybernetically enhanced web apps',
    created_at: 'Sun Nov 20 2016',
    updated_at: 'Mon Dec 20 2021',
    pushed_at: 'Sun Dec 19 2021',
    homepage: 'https://svelte.dev',
    stargazers_count: 53935,
    language: 'TypeScript',
    forks_count: 2584,
    open_issues_count: 604,
    license: 'MIT License',
    topics: ['compiler', 'template', 'ui'],
    subscribers_count: 874,
    has_projects: true,
    has_wiki: true,
    has_pages: false,
    closed_issues_count: 3549,
    open_pr_count: 104,
    closed_pr_count: 2738,
    week_issue_change: 14,
    stats: [53935, 2584, 604, 874, 104],
  },
  {
    id: 224663696,
    name: 'alpine',
    full_name: 'alpinejs/alpine',
    html_url: 'https://github.com/alpinejs/alpine',
    description:
      'A rugged, minimal framework for composing JavaScript behavior in your markup. ',
    created_at: 'Thu Nov 28 2019',
    updated_at: 'Mon Dec 20 2021',
    pushed_at: 'Tue Dec 14 2021',
    homepage: 'https://alpinejs.dev',
    stargazers_count: 19338,
    language: 'HTML',
    forks_count: 837,
    open_issues_count: 19,
    license: 'MIT License',
    topics: [],
    subscribers_count: 202,
    has_projects: false,
    has_wiki: false,
    has_pages: false,
    closed_issues_count: 544,
    open_pr_count: 13,
    closed_pr_count: 546,
    week_issue_change: 21,
    stats: [19338, 837, 19, 202, 13],
  },
  {
    id: 95797174,
    name: 'lit',
    full_name: 'lit/lit',
    html_url: 'https://github.com/lit/lit',
    description:
      'Lit is a simple library for building fast, lightweight web components.',
    created_at: 'Thu Jun 29 2017',
    updated_at: 'Mon Dec 20 2021',
    pushed_at: 'Fri Dec 17 2021',
    homepage: 'https://lit.dev',
    stargazers_count: 9752,
    language: 'JavaScript',
    forks_count: 528,
    open_issues_count: 207,
    license: 'BSD 3-Clause',
    topics: ['html-templates', 'lit', 'lit-element', 'lit-html'],
    subscribers_count: 204,
    has_projects: true,
    has_wiki: true,
    has_pages: false,
    closed_issues_count: 895,
    open_pr_count: 53,
    closed_pr_count: 1138,
    week_issue_change: -45,
    stats: [9752, 528, 207, 204, 53],
  },
  {
    id: 76694515,
    name: 'stimulus',
    full_name: 'hotwired/stimulus',
    html_url: 'https://github.com/hotwired/stimulus',
    description: 'A modest JavaScript framework for the HTML you already have',
    created_at: 'Sat Dec 17 2016',
    updated_at: 'Mon Dec 20 2021',
    pushed_at: 'Fri Dec 17 2021',
    homepage: 'https://stimulus.hotwired.dev/',
    stargazers_count: 11049,
    language: 'TypeScript',
    forks_count: 316,
    open_issues_count: 17,
    license: 'MIT License',
    topics: [],
    subscribers_count: 221,
    has_projects: false,
    has_wiki: true,
    has_pages: false,
    closed_issues_count: 282,
    open_pr_count: 5,
    closed_pr_count: 191,
    week_issue_change: -11,
    stats: [11049, 316, 17, 221, 5],
  },
  {
    id: 1801829,
    name: 'ember.js',
    full_name: 'emberjs/ember.js',
    html_url: 'https://github.com/emberjs/ember.js',
    description:
      'Ember.js - A JavaScript framework for creating ambitious web applications',
    created_at: 'Wed May 25 2011',
    updated_at: 'Sun Dec 19 2021',
    pushed_at: 'Mon Dec 20 2021',
    homepage: 'https://emberjs.com',
    stargazers_count: 22093,
    language: 'JavaScript',
    forks_count: 4253,
    open_issues_count: 427,
    license: 'MIT License',
    topics: ['ember', 'hacktoberfest', 'javascript', 'javascript-framework'],
    subscribers_count: 908,
    has_projects: true,
    has_wiki: false,
    has_pages: false,
    closed_issues_count: 6187,
    open_pr_count: 94,
    closed_pr_count: 9574,
    week_issue_change: -22,
    stats: [22093, 4253, 427, 908, 94],
  },
  {
    id: 82095231,
    name: 'stencil',
    full_name: 'ionic-team/stencil',
    html_url: 'https://github.com/ionic-team/stencil',
    description:
      'A toolchain for building scalable, enterprise-ready component systems on top of TypeScript.',
    created_at: 'Wed Feb 15 2017',
    updated_at: 'Mon Dec 20 2021',
    pushed_at: 'Thu Dec 16 2021',
    homepage: 'https://stenciljs.com',
    stargazers_count: 9884,
    language: 'TypeScript',
    forks_count: 641,
    open_issues_count: 499,
    license: 'Other',
    topics: [
      'custom-elements',
      'ionic',
      'progressive-web-app',
      'pwa',
      'ssg',
      'ssr',
      'static-site-generator',
      'stencil',
      'stenciljs',
      'typescript',
      'webcomponents',
    ],
    subscribers_count: 203,
    has_projects: true,
    has_wiki: false,
    has_pages: false,
    closed_issues_count: 1929,
    open_pr_count: 46,
    closed_pr_count: 743,
    week_issue_change: 12,
    stats: [9884, 641, 499, 203, 46],
  },
  {
    id: 130884470,
    name: 'solid',
    full_name: 'solidjs/solid',
    html_url: 'https://github.com/solidjs/solid',
    description:
      'A declarative, efficient, and flexible JavaScript library for building user interfaces.',
    created_at: 'Tue Apr 24 2018',
    updated_at: 'Mon Dec 20 2021',
    pushed_at: 'Sun Dec 19 2021',
    homepage: 'https://solidjs.com',
    stargazers_count: 13119,
    language: 'TypeScript',
    forks_count: 330,
    open_issues_count: 21,
    license: 'MIT License',
    topics: [
      'declarative',
      'fine-grained',
      'javascript',
      'jsx',
      'performance',
      'proxies',
      'reactive',
      'solid',
    ],
    subscribers_count: 161,
    has_projects: true,
    has_wiki: true,
    has_pages: false,
    closed_issues_count: 366,
    open_pr_count: 3,
    closed_pr_count: 164,
    week_issue_change: 23,
    stats: [13119, 330, 21, 161, 3],
  },
  {
    id: 17814354,
    name: 'mithril.js',
    full_name: 'MithrilJS/mithril.js',
    html_url: 'https://github.com/MithrilJS/mithril.js',
    description: 'A JavaScript Framework for Building Brilliant Applications',
    created_at: 'Mon Mar 17 2014',
    updated_at: 'Mon Dec 20 2021',
    pushed_at: 'Wed Nov 24 2021',
    homepage: 'https://mithril.js.org',
    stargazers_count: 13064,
    language: 'JavaScript',
    forks_count: 940,
    open_issues_count: 173,
    license: 'MIT License',
    topics: [
      'framework',
      'javascript',
      'mithril',
      'router',
      'vdom',
      'virtual-dom',
      'xhr',
    ],
    subscribers_count: 324,
    has_projects: true,
    has_wiki: true,
    has_pages: true,
    closed_issues_count: 1368,
    open_pr_count: 28,
    closed_pr_count: 1144,
    week_issue_change: 57,
    stats: [13064, 940, 173, 324, 28],
  },
  {
    id: 167174,
    name: 'jquery',
    full_name: 'jquery/jquery',
    html_url: 'https://github.com/jquery/jquery',
    description: 'jQuery JavaScript Library',
    created_at: 'Fri Apr 03 2009',
    updated_at: 'Mon Dec 20 2021',
    pushed_at: 'Fri Dec 17 2021',
    homepage: 'https://jquery.com',
    stargazers_count: 55666,
    language: 'JavaScript',
    forks_count: 20187,
    open_issues_count: 84,
    license: 'MIT License',
    topics: ['jquery'],
    subscribers_count: 3306,
    has_projects: true,
    has_wiki: true,
    has_pages: false,
    closed_issues_count: 2083,
    open_pr_count: 13,
    closed_pr_count: 2692,
    week_issue_change: 15,
    stats: [55666, 20187, 84, 3306, 13],
  },
  {
    id: 5532320,
    name: 'polymer',
    full_name: 'Polymer/polymer',
    html_url: 'https://github.com/Polymer/polymer',
    description: 'Our original Web Component library.',
    created_at: 'Thu Aug 23 2012',
    updated_at: 'Sun Dec 19 2021',
    pushed_at: 'Tue Dec 07 2021',
    homepage: 'https://polymer-library.polymer-project.org/',
    stargazers_count: 21724,
    language: 'HTML',
    forks_count: 2026,
    open_issues_count: 281,
    license: 'Other',
    topics: ['polymer', 'web-components'],
    subscribers_count: 894,
    has_projects: true,
    has_wiki: true,
    has_pages: false,
    closed_issues_count: 3648,
    open_pr_count: 26,
    closed_pr_count: 1404,
    week_issue_change: 9,
    stats: [21724, 2026, 281, 894, 26],
  },
  {
    id: 952189,
    name: 'backbone',
    full_name: 'jashkenas/backbone',
    html_url: 'https://github.com/jashkenas/backbone',
    description:
      'Give your JS App some Backbone with Models, Views, Collections, and Events',
    created_at: 'Thu Sep 30 2010',
    updated_at: 'Sun Dec 19 2021',
    pushed_at: 'Tue May 19 2020',
    homepage: 'http://backbonejs.org',
    stargazers_count: 27840,
    language: 'JavaScript',
    forks_count: 5608,
    open_issues_count: 85,
    license: 'MIT License',
    topics: [],
    subscribers_count: 1365,
    has_projects: true,
    has_wiki: true,
    has_pages: true,
    closed_issues_count: 2335,
    open_pr_count: 32,
    closed_pr_count: 1797,
    week_issue_change: -14,
    stats: [27840, 5608, 85, 1365, 32],
  },
  {
    id: 757363,
    name: 'knockout',
    full_name: 'knockout/knockout',
    html_url: 'https://github.com/knockout/knockout',
    description:
      'Knockout makes it easier to create rich, responsive UIs with JavaScript',
    created_at: 'Mon Jul 05 2010',
    updated_at: 'Sat Dec 18 2021',
    pushed_at: 'Sat Oct 09 2021',
    homepage: 'http://knockoutjs.com/',
    stargazers_count: 10122,
    language: 'JavaScript',
    forks_count: 1571,
    open_issues_count: 362,
    license: 'Other',
    topics: ['data-binding', 'javascript', 'knockout', 'mvvm'],
    subscribers_count: 549,
    has_projects: true,
    has_wiki: true,
    has_pages: true,
    closed_issues_count: 1534,
    open_pr_count: 72,
    closed_pr_count: 670,
    week_issue_change: 63,
    stats: [10122, 1571, 362, 549, 72],
  },
  {
    id: 191051391,
    name: 'redwood',
    full_name: 'redwoodjs/redwood',
    html_url: 'https://github.com/redwoodjs/redwood',
    description: 'The App Framework for Startups',
    created_at: 'Sun Jun 09 2019',
    updated_at: 'Mon Dec 20 2021',
    pushed_at: 'Mon Dec 20 2021',
    homepage: 'https://redwoodjs.com',
    stargazers_count: 10334,
    language: 'TypeScript',
    forks_count: 431,
    open_issues_count: 269,
    license: 'MIT License',
    topics: [
      'apollo',
      'graphql',
      'hacktoberfest',
      'jamstack',
      'prisma',
      'react',
    ],
    subscribers_count: 80,
    has_projects: true,
    has_wiki: true,
    has_pages: false,
    closed_issues_count: 1071,
    open_pr_count: 35,
    closed_pr_count: 2602,
    week_issue_change: 14,
    stats: [10334, 431, 269, 80, 35],
  },
  {
    id: 36040894,
    name: 'gatsby',
    full_name: 'gatsbyjs/gatsby',
    html_url: 'https://github.com/gatsbyjs/gatsby',
    description: 'Build blazing fast, modern apps and websites with React',
    created_at: 'Thu May 21 2015',
    updated_at: 'Mon Dec 20 2021',
    pushed_at: 'Mon Dec 20 2021',
    homepage: 'https://www.gatsbyjs.com',
    stargazers_count: 51931,
    language: 'JavaScript',
    forks_count: 10049,
    open_issues_count: 359,
    license: 'MIT License',
    topics: [
      'blog',
      'compiler',
      'documentation-tool',
      'gatsby',
      'graphql',
      'react',
      'static-site-generator',
      'web-app',
    ],
    subscribers_count: 853,
    has_projects: true,
    has_wiki: false,
    has_pages: false,
    closed_issues_count: 12975,
    open_pr_count: 180,
    closed_pr_count: 19058,
    week_issue_change: -34,
    stats: [51931, 10049, 359, 853, 180],
  },
  {
    id: 26316966,
    name: 'cyclejs',
    full_name: 'cyclejs/cyclejs',
    html_url: 'https://github.com/cyclejs/cyclejs',
    description:
      'A functional and reactive JavaScript framework for predictable code',
    created_at: 'Fri Nov 07 2014',
    updated_at: 'Mon Dec 20 2021',
    pushed_at: 'Fri Dec 17 2021',
    homepage: 'http://cycle.js.org',
    stargazers_count: 9999,
    language: 'TypeScript',
    forks_count: 421,
    open_issues_count: 102,
    license: 'MIT License',
    topics: [
      'cyclejs',
      'framework',
      'functional-programming',
      'hacktoberfest',
      'javascript',
      'reactive-programming',
      'rxjs',
      'typescript',
    ],
    subscribers_count: 205,
    has_projects: true,
    has_wiki: true,
    has_pages: true,
    closed_issues_count: 563,
    open_pr_count: 26,
    closed_pr_count: 301,
    week_issue_change: -2,
    stats: [9999, 421, 102, 205, 26],
  },
  {
    id: 42283287,
    name: 'preact',
    full_name: 'preactjs/preact',
    html_url: 'https://github.com/preactjs/preact',
    description:
      '⚛️ Fast 3kB React alternative with the same modern API. Components & Virtual DOM.',
    created_at: 'Fri Sep 11 2015',
    updated_at: 'Mon Dec 20 2021',
    pushed_at: 'Fri Dec 17 2021',
    homepage: 'https://preactjs.com',
    stargazers_count: 30538,
    language: 'JavaScript',
    forks_count: 1702,
    open_issues_count: 222,
    license: 'MIT License',
    topics: [
      'components',
      'dom',
      'jsx',
      'preact',
      'react',
      'vdom',
      'virtual-dom',
    ],
    subscribers_count: 425,
    has_projects: true,
    has_wiki: true,
    has_pages: true,
    closed_issues_count: 1309,
    open_pr_count: 78,
    closed_pr_count: 1729,
    week_issue_change: -12,
    stats: [30538, 1702, 222, 425, 78],
  },
  {
    id: 13142126,
    name: 'riot',
    full_name: 'riot/riot',
    html_url: 'https://github.com/riot/riot',
    description: 'Simple and elegant component-based UI library',
    created_at: 'Fri Sep 27 2013',
    updated_at: 'Mon Dec 20 2021',
    pushed_at: 'Fri Dec 17 2021',
    homepage: 'https://riot.js.org',
    stargazers_count: 14597,
    language: 'JavaScript',
    forks_count: 1032,
    open_issues_count: 5,
    license: 'Other',
    topics: [
      'client-side',
      'customelement',
      'customelements',
      'customtags',
      'elegant',
      'framework',
      'javascript',
      'lite',
      'minimal',
      'simple',
      'view',
      'webcomponents',
    ],
    subscribers_count: 412,
    has_projects: true,
    has_wiki: false,
    has_pages: false,
    closed_issues_count: 2147,
    open_pr_count: 0,
    closed_pr_count: 755,
    week_issue_change: 0,
    stats: [14597, 1032, 5, 412, 0],
  },
  {
    id: 121594173,
    name: 'aurelia',
    full_name: 'aurelia/aurelia',
    html_url: 'https://github.com/aurelia/aurelia',
    description:
      'Aurelia 2, a standards-based, front-end framework designed for high-performing, ambitious applications.',
    created_at: 'Thu Feb 15 2018',
    updated_at: 'Sun Dec 19 2021',
    pushed_at: 'Sun Nov 28 2021',
    homepage: '',
    stargazers_count: 1142,
    language: 'TypeScript',
    forks_count: 121,
    open_issues_count: 143,
    license: 'MIT License',
    topics: [
      'aurelia',
      'cordova',
      'cross-platform',
      'electron',
      'framework',
      'frontend',
      'html',
      'javascript',
      'javascript-framework',
      'mobile',
      'pwa',
      'single-page-applications',
      'spa',
      'typescript',
      'web',
      'web-framework',
      'web-performance',
    ],
    subscribers_count: 66,
    has_projects: true,
    has_wiki: false,
    has_pages: false,
    closed_issues_count: 214,
    open_pr_count: 17,
    closed_pr_count: 959,
    week_issue_change: 32,
    stats: [1142, 121, 143, 66, 17],
  },
  {
    id: 70107786,
    name: 'next.js',
    full_name: 'vercel/next.js',
    html_url: 'https://github.com/vercel/next.js',
    description: 'The React Framework',
    created_at: 'Wed Oct 05 2016',
    updated_at: 'Mon Dec 20 2021',
    pushed_at: 'Mon Dec 20 2021',
    homepage: 'https://nextjs.org',
    stargazers_count: 78446,
    language: 'JavaScript',
    forks_count: 15787,
    open_issues_count: 1361,
    license: 'MIT License',
    topics: [
      'blog',
      'browser',
      'compiler',
      'components',
      'hybrid',
      'nextjs',
      'node',
      'react',
      'server-rendering',
      'ssg',
      'static',
      'static-site-generator',
      'universal',
      'vercel',
    ],
    subscribers_count: 1224,
    has_projects: false,
    has_wiki: false,
    has_pages: false,
    closed_issues_count: 10320,
    open_pr_count: 254,
    closed_pr_count: 9849,
    week_issue_change: 63,
    stats: [78446, 15787, 1361, 1224, 254],
  },
  {
    id: 71995937,
    name: 'nuxt.js',
    full_name: 'nuxt/nuxt.js',
    html_url: 'https://github.com/nuxt/nuxt.js',
    description: 'The Intuitive Vue(2) Framework',
    created_at: 'Wed Oct 26 2016',
    updated_at: 'Mon Dec 20 2021',
    pushed_at: 'Mon Dec 20 2021',
    homepage: 'https://nuxtjs.org',
    stargazers_count: 38997,
    language: 'JavaScript',
    forks_count: 3157,
    open_issues_count: 464,
    license: 'Other',
    topics: [
      'framework',
      'isomorphic',
      'nuxt',
      'server-rendering',
      'ssr',
      'universal',
      'vue',
      'vue-router',
      'vuex',
      'web-app',
    ],
    subscribers_count: 772,
    has_projects: true,
    has_wiki: true,
    has_pages: false,
    closed_issues_count: 6129,
    open_pr_count: 30,
    closed_pr_count: 2869,
    week_issue_change: -18,
    stats: [38997, 3157, 464, 772, 30],
  },
  {
    id: 3214406,
    name: 'meteor',
    full_name: 'meteor/meteor',
    html_url: 'https://github.com/meteor/meteor',
    description: 'Meteor, the JavaScript App Platform',
    created_at: 'Thu Jan 19 2012',
    updated_at: 'Mon Dec 20 2021',
    pushed_at: 'Fri Dec 17 2021',
    homepage: 'https://www.meteor.com',
    stargazers_count: 42742,
    language: 'JavaScript',
    forks_count: 5187,
    open_issues_count: 120,
    license: 'Other',
    topics: [
      'build-system',
      'framework',
      'hacktoberfest',
      'javascript',
      'meteor',
      'mongodb',
      'nodejs',
      'npm',
      'reactive-programming',
      'zero-configuration',
    ],
    subscribers_count: 1642,
    has_projects: true,
    has_wiki: true,
    has_pages: false,
    closed_issues_count: 8537,
    open_pr_count: 24,
    closed_pr_count: 2998,
    week_issue_change: 21,
    stats: [42742, 5187, 120, 1642, 24],
  },
  {
    id: 43695474,
    name: 'quasar',
    full_name: 'quasarframework/quasar',
    html_url: 'https://github.com/quasarframework/quasar',
    description:
      'Quasar Framework - Build high-performance VueJS user interfaces in record time',
    created_at: 'Mon Oct 05 2015',
    updated_at: 'Mon Dec 20 2021',
    pushed_at: 'Sun Dec 19 2021',
    homepage: 'https://quasar.dev',
    stargazers_count: 20095,
    language: 'JavaScript',
    forks_count: 2543,
    open_issues_count: 367,
    license: 'MIT License',
    topics: [
      'android',
      'browser-extension',
      'electron',
      'ios',
      'javascript',
      'material',
      'material-components',
      'material-design',
      'material-theme',
      'pwa',
      'quasar-framework',
      'server-side-rendering',
      'ssr',
      'vue',
      'vue-component',
      'vue-components',
      'vue2',
      'vuejs',
      'vuejs2',
    ],
    subscribers_count: 488,
    has_projects: false,
    has_wiki: false,
    has_pages: false,
    closed_issues_count: 6097,
    open_pr_count: 97,
    closed_pr_count: 3424,
    week_issue_change: 1,
    stats: [20095, 2543, 367, 488, 97],
  },
];
