[functions]
  directory = "www/functions"
  node_bundler = "esbuild"
  included_files = ["www/dataserver/data/**.json"]
  external_node_modules = ["express", "serverless-http", "path", "cors", "body-parser", "json-server","fs","net","tls","request","xlsx","alasql"]

[[headers]]
  for = "/*"
  [headers.values]
  cache-control = "no-store"
[[headers]]
  for = "*.css"
  [headers.values]
    cache-control = '''
    public,
    max-age=31536000,
    immutable'''
[[headers]]
  for = "*.js"
  [headers.values]
    cache-control = '''
    public,
    max-age=31536000,
    immutable'''
