export type FileSystemNode = {
  id: string;
  name: string;
  type: 'folder' | 'file';
  extension?: string;
  mimeType?: string;
  sizeInKB: number;
  children?: FileSystemNode[];
};

export const dataSource = () => {
  const nodes: FileSystemNode[] = [
    {
      id: '1',
      name: 'Documents',
      sizeInKB: 15400,
      type: 'folder',
      children: [
        {
          id: '10',
          name: 'Report.docx',
          sizeInKB: 210,
          type: 'file',
          extension: 'docx',
          mimeType: 'application/msword',
        },
        {
          id: '11',
          name: 'Budget.xlsx',
          sizeInKB: 340,
          type: 'file',
          extension: 'xlsx',
          mimeType: 'application/vnd.ms-excel',
        },
        {
          id: '12',
          name: 'Presentation.pptx',
          sizeInKB: 1200,
          type: 'file',
          extension: 'pptx',
          mimeType: 'application/vnd.ms-powerpoint',
        },
        {
          id: '13',
          name: 'Notes.txt',
          sizeInKB: 45,
          type: 'file',
          extension: 'txt',
          mimeType: 'text/plain',
        },
        {
          id: '14',
          name: 'Contract.pdf',
          sizeInKB: 890,
          type: 'file',
          extension: 'pdf',
          mimeType: 'application/pdf',
        },
        {
          id: '15',
          name: 'Invoice.pdf',
          sizeInKB: 120,
          type: 'file',
          extension: 'pdf',
          mimeType: 'application/pdf',
        },
        {
          id: '16',
          name: 'Meeting-Minutes.docx',
          sizeInKB: 180,
          type: 'file',
          extension: 'docx',
          mimeType: 'application/msword',
        },
        {
          id: '17',
          name: 'Project-Plan.xlsx',
          sizeInKB: 560,
          type: 'file',
          extension: 'xlsx',
          mimeType: 'application/vnd.ms-excel',
        },
        {
          id: '18',
          name: 'Resume.pdf',
          sizeInKB: 230,
          type: 'file',
          extension: 'pdf',
          mimeType: 'application/pdf',
        },
        {
          id: '19',
          name: 'Cover-Letter.docx',
          sizeInKB: 95,
          type: 'file',
          extension: 'docx',
          mimeType: 'application/msword',
        },
        {
          id: '110',
          name: 'Timesheet.xlsx',
          sizeInKB: 280,
          type: 'file',
          extension: 'xlsx',
          mimeType: 'application/vnd.ms-excel',
        },
        {
          id: '111',
          name: 'Proposal.pdf',
          sizeInKB: 670,
          type: 'file',
          extension: 'pdf',
          mimeType: 'application/pdf',
        },
        {
          id: '112',
          name: 'Agenda.docx',
          sizeInKB: 110,
          type: 'file',
          extension: 'docx',
          mimeType: 'application/msword',
        },
        {
          id: '113',
          name: 'Financial-Report.xlsx',
          sizeInKB: 920,
          type: 'file',
          extension: 'xlsx',
          mimeType: 'application/vnd.ms-excel',
        },
        {
          id: '114',
          name: 'Memo.txt',
          sizeInKB: 32,
          type: 'file',
          extension: 'txt',
          mimeType: 'text/plain',
        },
        {
          id: '115',
          name: 'Policy.pdf',
          sizeInKB: 540,
          type: 'file',
          extension: 'pdf',
          mimeType: 'application/pdf',
        },
        {
          id: '116',
          name: 'Guidelines.docx',
          sizeInKB: 310,
          type: 'file',
          extension: 'docx',
          mimeType: 'application/msword',
        },
        {
          id: '117',
          name: 'Schedule.xlsx',
          sizeInKB: 190,
          type: 'file',
          extension: 'xlsx',
          mimeType: 'application/vnd.ms-excel',
        },
        {
          id: '118',
          name: 'Summary.pdf',
          sizeInKB: 420,
          type: 'file',
          extension: 'pdf',
          mimeType: 'application/pdf',
        },
        {
          id: '119',
          name: 'Checklist.txt',
          sizeInKB: 28,
          type: 'file',
          extension: 'txt',
          mimeType: 'text/plain',
        },
      ],
    },
    {
      id: '2',
      name: 'Desktop',
      sizeInKB: 8900,
      type: 'folder',
      children: [
        {
          id: '20',
          name: 'Screenshot-1.png',
          sizeInKB: 450,
          type: 'file',
          extension: 'png',
          mimeType: 'image/png',
        },
        {
          id: '21',
          name: 'Screenshot-2.png',
          sizeInKB: 520,
          type: 'file',
          extension: 'png',
          mimeType: 'image/png',
        },
        {
          id: '22',
          name: 'TODO.txt',
          sizeInKB: 15,
          type: 'file',
          extension: 'txt',
          mimeType: 'text/plain',
        },
        {
          id: '23',
          name: 'Shortcut.lnk',
          sizeInKB: 2,
          type: 'file',
          extension: 'lnk',
          mimeType: 'application/x-ms-shortcut',
        },
        {
          id: '24',
          name: 'Wallpaper.jpg',
          sizeInKB: 1200,
          type: 'file',
          extension: 'jpg',
          mimeType: 'image/jpeg',
        },
        {
          id: '25',
          name: 'Icon.ico',
          sizeInKB: 48,
          type: 'file',
          extension: 'ico',
          mimeType: 'image/x-icon',
        },
        {
          id: '26',
          name: 'Backup.zip',
          sizeInKB: 3400,
          type: 'file',
          extension: 'zip',
          mimeType: 'application/zip',
        },
        {
          id: '27',
          name: 'Config.json',
          sizeInKB: 12,
          type: 'file',
          extension: 'json',
          mimeType: 'application/json',
        },
        {
          id: '28',
          name: 'Data.csv',
          sizeInKB: 340,
          type: 'file',
          extension: 'csv',
          mimeType: 'text/csv',
        },
        {
          id: '29',
          name: 'Log.txt',
          sizeInKB: 89,
          type: 'file',
          extension: 'txt',
          mimeType: 'text/plain',
        },
        {
          id: '210',
          name: 'Archive.rar',
          sizeInKB: 2100,
          type: 'file',
          extension: 'rar',
          mimeType: 'application/x-rar-compressed',
        },
        {
          id: '211',
          name: 'Temp.tmp',
          sizeInKB: 56,
          type: 'file',
          extension: 'tmp',
          mimeType: 'application/octet-stream',
        },
        {
          id: '212',
          name: 'Settings.xml',
          sizeInKB: 23,
          type: 'file',
          extension: 'xml',
          mimeType: 'application/xml',
        },
        {
          id: '213',
          name: 'Readme.md',
          sizeInKB: 18,
          type: 'file',
          extension: 'md',
          mimeType: 'text/markdown',
        },
        {
          id: '214',
          name: 'Photo.jpg',
          sizeInKB: 890,
          type: 'file',
          extension: 'jpg',
          mimeType: 'image/jpeg',
        },
        {
          id: '215',
          name: 'Diagram.svg',
          sizeInKB: 67,
          type: 'file',
          extension: 'svg',
          mimeType: 'image/svg+xml',
        },
        {
          id: '216',
          name: 'Script.sh',
          sizeInKB: 8,
          type: 'file',
          extension: 'sh',
          mimeType: 'application/x-sh',
        },
        {
          id: '217',
          name: 'Database.db',
          sizeInKB: 450,
          type: 'file',
          extension: 'db',
          mimeType: 'application/x-sqlite3',
        },
        {
          id: '218',
          name: 'Certificate.pem',
          sizeInKB: 4,
          type: 'file',
          extension: 'pem',
          mimeType: 'application/x-pem-file',
        },
        {
          id: '219',
          name: 'Key.key',
          sizeInKB: 2,
          type: 'file',
          extension: 'key',
          mimeType: 'application/octet-stream',
        },
      ],
    },
    {
      id: '3',
      name: 'Media',
      sizeInKB: 45600,
      type: 'folder',
      children: [
        {
          id: '30',
          name: 'Vacation.mp4',
          sizeInKB: 5400,
          type: 'file',
          extension: 'mp4',
          mimeType: 'video/mp4',
        },
        {
          id: '31',
          name: 'Birthday.mp4',
          sizeInKB: 3200,
          type: 'file',
          extension: 'mp4',
          mimeType: 'video/mp4',
        },
        {
          id: '32',
          name: 'Wedding.mov',
          sizeInKB: 8900,
          type: 'file',
          extension: 'mov',
          mimeType: 'video/quicktime',
        },
        {
          id: '33',
          name: 'Song1.mp3',
          sizeInKB: 4500,
          type: 'file',
          extension: 'mp3',
          mimeType: 'audio/mpeg',
        },
        {
          id: '34',
          name: 'Song2.mp3',
          sizeInKB: 3800,
          type: 'file',
          extension: 'mp3',
          mimeType: 'audio/mpeg',
        },
        {
          id: '35',
          name: 'Podcast.mp3',
          sizeInKB: 12000,
          type: 'file',
          extension: 'mp3',
          mimeType: 'audio/mpeg',
        },
        {
          id: '36',
          name: 'Album-Cover.jpg',
          sizeInKB: 340,
          type: 'file',
          extension: 'jpg',
          mimeType: 'image/jpeg',
        },
        {
          id: '37',
          name: 'Concert.mp4',
          sizeInKB: 6700,
          type: 'file',
          extension: 'mp4',
          mimeType: 'video/mp4',
        },
        {
          id: '38',
          name: 'Interview.wav',
          sizeInKB: 15600,
          type: 'file',
          extension: 'wav',
          mimeType: 'audio/wav',
        },
        {
          id: '39',
          name: 'Trailer.mp4',
          sizeInKB: 2300,
          type: 'file',
          extension: 'mp4',
          mimeType: 'video/mp4',
        },
        {
          id: '310',
          name: 'Audiobook.m4a',
          sizeInKB: 8900,
          type: 'file',
          extension: 'm4a',
          mimeType: 'audio/mp4',
        },
        {
          id: '311',
          name: 'Tutorial.mp4',
          sizeInKB: 4500,
          type: 'file',
          extension: 'mp4',
          mimeType: 'video/mp4',
        },
        {
          id: '312',
          name: 'Ringtone.mp3',
          sizeInKB: 450,
          type: 'file',
          extension: 'mp3',
          mimeType: 'audio/mpeg',
        },
        {
          id: '313',
          name: 'Voicemail.wav',
          sizeInKB: 890,
          type: 'file',
          extension: 'wav',
          mimeType: 'audio/wav',
        },
        {
          id: '314',
          name: 'Presentation-Video.mp4',
          sizeInKB: 7800,
          type: 'file',
          extension: 'mp4',
          mimeType: 'video/mp4',
        },
        {
          id: '315',
          name: 'Background-Music.mp3',
          sizeInKB: 3400,
          type: 'file',
          extension: 'mp3',
          mimeType: 'audio/mpeg',
        },
        {
          id: '316',
          name: 'Sound-Effect.wav',
          sizeInKB: 120,
          type: 'file',
          extension: 'wav',
          mimeType: 'audio/wav',
        },
        {
          id: '317',
          name: 'Animation.gif',
          sizeInKB: 2300,
          type: 'file',
          extension: 'gif',
          mimeType: 'image/gif',
        },
        {
          id: '318',
          name: 'Thumbnail.png',
          sizeInKB: 180,
          type: 'file',
          extension: 'png',
          mimeType: 'image/png',
        },
        {
          id: '319',
          name: 'Subtitle.srt',
          sizeInKB: 45,
          type: 'file',
          extension: 'srt',
          mimeType: 'text/plain',
        },
      ],
    },
  ];

  return Promise.resolve(nodes);
};
