'use client';
import * as React from 'react';

import { IconCopy } from './icons/IconCopy';
import { IconCheck } from './icons/IconCheck';

/**
 * Actions for the LLM-friendly markdown version of a docs page
 * (generated by scripts/generate-llms-docs.js).
 */
export function CopyMarkdownButton(props: { mdPath: string }) {
  const timeoutIdRef = React.useRef<number | null>(null);
  const [copied, setCopied] = React.useState(false);

  async function onCopy() {
    try {
      const response = await fetch(props.mdPath);
      if (!response.ok) {
        return;
      }
      await navigator.clipboard.writeText(await response.text());
    } catch {
      return;
    }

    setCopied(true);
    if (timeoutIdRef.current) {
      clearTimeout(timeoutIdRef.current);
    }
    timeoutIdRef.current = setTimeout(() => {
      setCopied(false);
    }, 2000) as any as number;
  }

  const cls =
    'inline-flex items-center gap-1.5 text-xs text-gray-300 bg-gray-800 hover:bg-gray-700 py-1 px-2 rounded-md cursor-pointer';

  return (
    <div className="flex items-center gap-2 mt-2 mb-4">
      <button
        type="button"
        className={cls}
        onClick={onCopy}
        title="Copy this page as markdown, for LLMs & AI tools"
      >
        {copied ? <IconCheck size={12} /> : <IconCopy size={12} />}
        {copied ? 'Copied' : 'Copy as Markdown'}
      </button>
      <a
        href={props.mdPath}
        target="_blank"
        rel="noopener noreferrer"
        className={cls}
        title="View this page as markdown"
      >
        View as Markdown
      </a>
    </div>
  );
}
