// AUTO-GENERATED by scripts/generate-theme-vars.cjs (repo root) - DO NOT EDIT MANUALLY.
// Source of truth: source/src/components/InfiniteTable/vars.css.ts
// Regenerate with: npm run generate-theme-vars (in the repo root)

export type ThemeVarKind = 'color' | 'text';

export type ThemeVarMeta = {
  name: string;
  label: string;
  group: string;
  kind: ThemeVarKind;
  description?: string;
};

export const THEME_VAR_GROUPS: string[] = [
  "Colors",
  "Spacing",
  "Typography",
  "General",
  "GroupingToolbar",
  "GroupingToolbarItem",
  "LoadMask",
  "Header",
  "HeaderCell",
  "ActiveCellIndicator",
  "Cell",
  "SelectionCheckBox",
  "ExpandCollapseIcon",
  "Menu",
  "RowDetail",
  "Row"
];

export const THEME_VARS: ThemeVarMeta[] = [
  {
    "name": "--infinite-accent-color",
    "label": "Accent",
    "group": "Colors",
    "kind": "color",
    "description": "Brand-specific accent color. This probably needs override to match your app."
  },
  {
    "name": "--infinite-success-color",
    "label": "Success",
    "group": "Colors",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-error-color",
    "label": "Error",
    "group": "Colors",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-color",
    "label": "Color",
    "group": "Colors",
    "kind": "color",
    "description": "The text color inside the component"
  },
  {
    "name": "--infinite-space-0",
    "label": "Spacing 0",
    "group": "Spacing",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-space-1",
    "label": "Spacing 1",
    "group": "Spacing",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-space-2",
    "label": "Spacing 2",
    "group": "Spacing",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-space-3",
    "label": "Spacing 3",
    "group": "Spacing",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-space-4",
    "label": "Spacing 4",
    "group": "Spacing",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-space-5",
    "label": "Spacing 5",
    "group": "Spacing",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-space-6",
    "label": "Spacing 6",
    "group": "Spacing",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-space-7",
    "label": "Spacing 7",
    "group": "Spacing",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-space-8",
    "label": "Spacing 8",
    "group": "Spacing",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-space-9",
    "label": "Spacing 9",
    "group": "Spacing",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-space-10",
    "label": "Spacing 10",
    "group": "Spacing",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-font-size-0",
    "label": "Font size 0",
    "group": "Typography",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-font-size-1",
    "label": "Font size 1",
    "group": "Typography",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-font-size-2",
    "label": "Font size 2",
    "group": "Typography",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-font-size-3",
    "label": "Font size 3",
    "group": "Typography",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-font-size-4",
    "label": "Font size 4",
    "group": "Typography",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-font-size-5",
    "label": "Font size 5",
    "group": "Typography",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-font-size-6",
    "label": "Font size 6",
    "group": "Typography",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-font-size-7",
    "label": "Font size 7",
    "group": "Typography",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-font-family",
    "label": "Font family",
    "group": "Typography",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-min-height",
    "label": "Min height",
    "group": "General",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-border-radius",
    "label": "Border radius",
    "group": "General",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-focus-outline",
    "label": "Focus outline",
    "group": "General",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-background",
    "label": "Background",
    "group": "Colors",
    "kind": "color",
    "description": "The background color for the whole component.\n\nOverriden in the `dark` theme."
  },
  {
    "name": "--infinite-icon-size",
    "label": "Icon size",
    "group": "General",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-grouping-toolbar-color",
    "label": "Color",
    "group": "GroupingToolbar",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-grouping-toolbar-background",
    "label": "Background",
    "group": "GroupingToolbar",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-grouping-toolbar-reject-background",
    "label": "Reject background",
    "group": "GroupingToolbar",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-grouping-toolbar-active-background",
    "label": "Active background",
    "group": "GroupingToolbar",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-grouping-toolbar-active-background-alpha",
    "label": "Active background alpha",
    "group": "GroupingToolbar",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-grouping-toolbar-padding",
    "label": "Padding",
    "group": "GroupingToolbar",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-grouping-toolbar-border",
    "label": "Border",
    "group": "GroupingToolbar",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-grouping-toolbar-reject-border",
    "label": "Reject border",
    "group": "GroupingToolbar",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-grouping-toolbar-gap",
    "label": "Gap",
    "group": "GroupingToolbar",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-grouping-toolbar-item-border",
    "label": "Border",
    "group": "GroupingToolbarItem",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-grouping-toolbar-item-border-radius",
    "label": "Border radius",
    "group": "GroupingToolbarItem",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-grouping-toolbar-item-active-border",
    "label": "Active border",
    "group": "GroupingToolbarItem",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-grouping-toolbar-item-background",
    "label": "Background",
    "group": "GroupingToolbarItem",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-grouping-toolbar-item-active-background",
    "label": "Active background",
    "group": "GroupingToolbarItem",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-grouping-toolbar-item-active-background-alpha",
    "label": "Active background alpha",
    "group": "GroupingToolbarItem",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-load-mask-padding",
    "label": "Padding",
    "group": "LoadMask",
    "kind": "text",
    "description": "The padding used for the content inside the LoadMask."
  },
  {
    "name": "--infinite-load-mask-color",
    "label": "Color",
    "group": "LoadMask",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-load-mask-text-background",
    "label": "Text background",
    "group": "LoadMask",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-load-mask-overlay-background",
    "label": "Overlay background",
    "group": "LoadMask",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-load-mask-overlay-opacity",
    "label": "Overlay opacity",
    "group": "LoadMask",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-load-mask-border-radius",
    "label": "Border radius",
    "group": "LoadMask",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-header-background",
    "label": "Background",
    "group": "Header",
    "kind": "color",
    "description": "Background color for the header. Defaults to [`--infinie-header-cell-background`](#header-cell-background).\n\nOverriden in the `dark` theme."
  },
  {
    "name": "--infinite-header-color",
    "label": "Color",
    "group": "Header",
    "kind": "color",
    "description": "The text color inside the header.\n\nOverriden in the `dark` theme."
  },
  {
    "name": "--infinite-column-header-height",
    "label": "Column header height",
    "group": "Header",
    "kind": "text",
    "description": "The height of the column header."
  },
  {
    "name": "--infinite-header-cell-background",
    "label": "Background",
    "group": "HeaderCell",
    "kind": "color",
    "description": "Background for header cells.\n\nOverriden in the `dark` theme."
  },
  {
    "name": "--infinite-header-cell-hover-background",
    "label": "Hover background",
    "group": "HeaderCell",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-header-cell-border",
    "label": "Border",
    "group": "HeaderCell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-header-cell-padding",
    "label": "Padding",
    "group": "HeaderCell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-header-cell-padding-x",
    "label": "Padding x",
    "group": "HeaderCell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-header-cell-padding-y",
    "label": "Padding y",
    "group": "HeaderCell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-header-cell-icon-size",
    "label": "Icon size",
    "group": "HeaderCell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-header-cell-menu-icon-line-width",
    "label": "Menu icon line width",
    "group": "HeaderCell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-header-cell-sort-icon-margin",
    "label": "Sort icon margin",
    "group": "HeaderCell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-header-cell-border-right",
    "label": "Border right",
    "group": "HeaderCell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-resize-handle-active-area-width",
    "label": "Resize handle active area width",
    "group": "HeaderCell",
    "kind": "text",
    "description": "The width of the area you can hover over in order to grab the column resize handle.\nDefaults to `20px`.\n\nThe purpose of this active area is to make it easier to grab the resize handle."
  },
  {
    "name": "--infinite-resize-handle-width",
    "label": "Resize handle width",
    "group": "HeaderCell",
    "kind": "text",
    "description": "The width of the colored column resize handle that is displayed on hover and on drag. Defaults to `2px`"
  },
  {
    "name": "--infinite-resize-handle-hover-background",
    "label": "Resize handle hover background",
    "group": "HeaderCell",
    "kind": "color",
    "description": "The color of the column resize handle - the resize handle is the visible indicator that you see\nwhen hovering over the right-edge of a resizable column. Also visible on drag while doing a column resize."
  },
  {
    "name": "--infinite-resize-handle-constrained-hover-background",
    "label": "Resize handle constrained hover background",
    "group": "HeaderCell",
    "kind": "color",
    "description": "The color of the column resize handle when it has reached a min/max constraint."
  },
  {
    "name": "--infinite-filter-operator-padding-x",
    "label": "Filter operator padding x",
    "group": "HeaderCell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-filter-editor-padding-x",
    "label": "Filter editor padding x",
    "group": "HeaderCell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-filter-editor-margin-x",
    "label": "Filter editor margin x",
    "group": "HeaderCell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-filter-operator-padding-y",
    "label": "Filter operator padding y",
    "group": "HeaderCell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-filter-editor-padding-y",
    "label": "Filter editor padding y",
    "group": "HeaderCell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-filter-editor-margin-y",
    "label": "Filter editor margin y",
    "group": "HeaderCell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-filter-editor-background",
    "label": "Filter editor background",
    "group": "HeaderCell",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-filter-editor-border",
    "label": "Filter editor border",
    "group": "HeaderCell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-filter-editor-focus-border-color",
    "label": "Filter editor focus border color",
    "group": "HeaderCell",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-filter-editor-border-radius",
    "label": "Filter editor border radius",
    "group": "HeaderCell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-filter-editor-color",
    "label": "Filter editor color",
    "group": "HeaderCell",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-active-cell-indicator-inset",
    "label": "Inset",
    "group": "ActiveCellIndicator",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-flashing-duration",
    "label": "Flashing duration",
    "group": "Cell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-flashing-animation-name",
    "label": "Flashing animation name",
    "group": "Cell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-flashing-overlay-z-index",
    "label": "Flashing overlay zindex",
    "group": "Cell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-flashing-background",
    "label": "Flashing background",
    "group": "Cell",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-flashing-up-background",
    "label": "Flashing up background",
    "group": "Cell",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-flashing-down-background",
    "label": "Flashing down background",
    "group": "Cell",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-cell-padding",
    "label": "Padding",
    "group": "Cell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-cell-border-width",
    "label": "Border width",
    "group": "Cell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-cell-border-color",
    "label": "Border color",
    "group": "Cell",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-cell-border",
    "label": "Border",
    "group": "Cell",
    "kind": "text",
    "description": "Specifies the border for cells.\n\nOverriden in the `dark` theme - eg: `1px solid #2a323d`"
  },
  {
    "name": "--infinite-cell-border-left",
    "label": "Border left",
    "group": "Cell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-cell-border-right",
    "label": "Border right",
    "group": "Cell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-cell-border-top",
    "label": "Border top",
    "group": "Cell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-cell-border-invisible",
    "label": "Border invisible",
    "group": "Cell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-cell-border-radius",
    "label": "Border radius",
    "group": "Cell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-column-reorder-effect-duration",
    "label": "Reorder effect duration",
    "group": "Cell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-pinned-cell-border",
    "label": "Pinned border",
    "group": "Cell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-horizontal-layout-column-reorder-disabled-page-opacity",
    "label": "Horizontal layout column reorder disabled page opacity",
    "group": "Cell",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-cell-color",
    "label": "Color",
    "group": "Cell",
    "kind": "color",
    "description": "Text color inside rows. Defaults to `currentColor`\n\nOverriden in `dark` theme."
  },
  {
    "name": "--infinite-selected-cell-background",
    "label": "Selected background",
    "group": "Cell",
    "kind": "color",
    "description": "The background for selected cells, when cell selection is enabled.\n\nIf not specified, it will default to `var(--infinite-active-cell-background)`."
  },
  {
    "name": "--infinite-selected-cell-background-default",
    "label": "Selected background default",
    "group": "Cell",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-selected-cell-background-alpha",
    "label": "Selected background alpha",
    "group": "Cell",
    "kind": "text",
    "description": "The opacity of the background color for the selected cell.\n\nIf not specified, it will default to the value for `var(--infinite-active-cell-background-alpha)`"
  },
  {
    "name": "--infinite-selected-cell-background-alpha--table-unfocused",
    "label": "Selected background alpha when table unfocused",
    "group": "Cell",
    "kind": "text",
    "description": "The opacity of the background color for the selected cell, when the table is unfocused.\nIf not specified, it will default to `var(--infinite-active-cell-background-alpha--table-unfocused)`."
  },
  {
    "name": "--infinite-selected-cell-border-color",
    "label": "Selected border color",
    "group": "Cell",
    "kind": "color",
    "description": "The color for border of the selected cell (when cell selection is enabled).\n Defaults to `var(--infinite-active-cell-border-color)`."
  },
  {
    "name": "--infinite-selected-cell-border-width",
    "label": "Selected border width",
    "group": "Cell",
    "kind": "text",
    "description": "The width of the border for the selected cell. Defaults to `var(--infinite-active-cell-border-width)`."
  },
  {
    "name": "--infinite-selected-cell-border-style",
    "label": "Selected border style",
    "group": "Cell",
    "kind": "text",
    "description": "The style of the border for the selected cell (eg: 'solid', 'dashed', 'dotted') - defaults to 'dashed'.\nDefaults to `var(--infinite-active-cell-border-style)`."
  },
  {
    "name": "--infinite-selected-cell-border",
    "label": "Selected border",
    "group": "Cell",
    "kind": "text",
    "description": "Specifies the border for the selected cell. Defaults to `var(--infinite-selected-cell-border-width) var(--infinite-selected-cell-border-style) var(--infinite-selected-cell-border-color)`."
  },
  {
    "name": "--infinite-active-cell-background-alpha",
    "label": "Active background alpha",
    "group": "Cell",
    "kind": "text",
    "description": "The opacity of the background color for the active cell (when cell keyboard navigation is enabled).\nEg: 0.25\n\nIf `activeBackground` is not explicitly defined (this is the default), the background color of the active cell\nis the same as the border color (`activeBorderColor`), but with this modified opacity.\n\nIf `activeBorderColor` is also not defined, the accent color will be used.\n\nThis is applied when the component has focus."
  },
  {
    "name": "--infinite-active-cell-background-alpha--table-unfocused",
    "label": "Active background alpha when table unfocused",
    "group": "Cell",
    "kind": "text",
    "description": "Same as the above, but applied when the component does not have focus."
  },
  {
    "name": "--infinite-active-cell-background",
    "label": "Active background",
    "group": "Cell",
    "kind": "color",
    "description": "The background color of the active cell.\n\nIf not specified, it will default to `activeBorderColor` with the opacity of `activeBackgroundAlpha`.\nIf `activeBorderColor` is not specified, it will default to the accent color, with the same opacity as mentioned.\n\nHowever, specify this to explicitly override the default."
  },
  {
    "name": "--infinite-active-cell-background-default",
    "label": "Active background default",
    "group": "Cell",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-active-cell-border-color",
    "label": "Active border color",
    "group": "Cell",
    "kind": "color",
    "description": "The color for border of the active cell (when cell keyboard navigation is enabled)."
  },
  {
    "name": "--infinite-active-cell-border-width",
    "label": "Active border width",
    "group": "Cell",
    "kind": "text",
    "description": "The width of the border for the active cell."
  },
  {
    "name": "--infinite-active-cell-border-style",
    "label": "Active border style",
    "group": "Cell",
    "kind": "text",
    "description": "The style of the border for the active cell (eg: 'solid', 'dashed', 'dotted') - defaults to 'dashed'."
  },
  {
    "name": "--infinite-active-cell-border",
    "label": "Active border",
    "group": "Cell",
    "kind": "text",
    "description": "Specifies the border for the active cell. Defaults to `var(--infinite-active-cell-border-width) var(--infinite-active-cell-border-style) var(--infinite-active-cell-border-color)`."
  },
  {
    "name": "--infinite-selection-checkbox-margin-inline",
    "label": "Margin inline",
    "group": "SelectionCheckBox",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-expand-collapse-icon-color",
    "label": "Color",
    "group": "ExpandCollapseIcon",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-menu-background",
    "label": "Background",
    "group": "Menu",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-menu-color",
    "label": "Color",
    "group": "Menu",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-menu-separator-color",
    "label": "Separator color",
    "group": "Menu",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-menu-padding",
    "label": "Padding",
    "group": "Menu",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-menu-cell-padding-vertical",
    "label": "Cell padding vertical",
    "group": "Menu",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-menu-cell-padding-horizontal",
    "label": "Cell padding horizontal",
    "group": "Menu",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-menu-cell-margin-vertical",
    "label": "Cell margin vertical",
    "group": "Menu",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-menu-item-disabled-background",
    "label": "Item disabled background",
    "group": "Menu",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-menu-item-active-background",
    "label": "Item active background",
    "group": "Menu",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-menu-item-active-opacity",
    "label": "Item active opacity",
    "group": "Menu",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-menu-item-pressed-opacity",
    "label": "Item pressed opacity",
    "group": "Menu",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-menu-item-pressed-background",
    "label": "Item pressed background",
    "group": "Menu",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-menu-item-disabled-opacity",
    "label": "Item disabled opacity",
    "group": "Menu",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-menu-border-radius",
    "label": "Border radius",
    "group": "Menu",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-menu-shadow-color",
    "label": "Shadow color",
    "group": "Menu",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-rowdetail-background",
    "label": "Background",
    "group": "RowDetail",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-rowdetail-padding",
    "label": "Padding",
    "group": "RowDetail",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-rowdetail-grid-height",
    "label": "Grid height",
    "group": "RowDetail",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-row-background",
    "label": "Background",
    "group": "Row",
    "kind": "color",
    "description": "Background color for rows. Defaults to [`--infinite-background`](#background).\n\nOverriden in `dark` theme."
  },
  {
    "name": "--infinite-row-odd-background",
    "label": "Odd background",
    "group": "Row",
    "kind": "color",
    "description": "Background color for odd rows. Even rows will use [`--infinite-row-background`](#row-background).\n\nOverriden in `dark` theme."
  },
  {
    "name": "--infinite-row-disabled-background",
    "label": "Disabled background",
    "group": "Row",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-row-odd-disabled-background",
    "label": "Odd disabled background",
    "group": "Row",
    "kind": "color",
    "description": "Background color for disabled rows. For setting the background of disabled even rows, use [`--infinite-row-disabled-background`](#row-disabled-background)."
  },
  {
    "name": "--infinite-row-selected-background",
    "label": "Selected background",
    "group": "Row",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-row-disabled-opacity",
    "label": "Disabled opacity",
    "group": "Row",
    "kind": "text",
    "description": "Opacity for disabled rows. Defaults to 0.5"
  },
  {
    "name": "--infinite-active-row-background",
    "label": "Active background",
    "group": "Row",
    "kind": "color",
    "description": "The background color of the active row. Defaults to the value of `var(--infinite-active-cell-background)`.\n\nHowever, specify this to explicitly override the default."
  },
  {
    "name": "--infinite-active-row-border-color",
    "label": "Active border color",
    "group": "Row",
    "kind": "color",
    "description": "The border color for the active row. Defaults to the value of `var(--infinite-active-cell-border-color)`."
  },
  {
    "name": "--infinite-active-row-border-width",
    "label": "Active border width",
    "group": "Row",
    "kind": "text",
    "description": "The width of the border for the active row. Defaults to the value of `var(--infinite-active-cell-border-width)`."
  },
  {
    "name": "--infinite-active-row-border-style",
    "label": "Active border style",
    "group": "Row",
    "kind": "text",
    "description": "The style of the border for the active row (eg: 'solid', 'dashed', 'dotted') - defaults to the value of `var(--infinite-active-cell-border-style)`, which is `dashed` by default."
  },
  {
    "name": "--infinite-active-row-border",
    "label": "Active border",
    "group": "Row",
    "kind": "text",
    "description": "Specifies the border for the active row. Defaults to `var(--infinite-active-row-border-width) var(--infinite-active-row-border-style) var(--infinite-active-row-border-color)`."
  },
  {
    "name": "--infinite-active-row-background-alpha",
    "label": "Active background alpha",
    "group": "Row",
    "kind": "text",
    "description": "The opacity of the background color for the active row (when row keyboard navigation is enabled).\nWhen you explicitly specify `--infinite-active-row-background`, this variable will not be used.\nInstead, this variable is used when the active row background uses the color of the active cell (border).\n\nThis is applied when the component has focus.\n\nDefaults to the value of `var(--infinite-active-cell-background-alpha)`."
  },
  {
    "name": "--infinite-active-row-background-alpha--table-unfocused",
    "label": "Active background alpha when table unfocused",
    "group": "Row",
    "kind": "text",
    "description": "Same as the above, but applied when the component does not have focus.\n\nWhen you explicitly specify `--infinite-active-row-background`, this variable will not be used.\nInstead, this variable is used when the active row background uses the color of the active cell (border).\n\nDefaults to the value of `var(--infinite-active-cell-background-alpha--table-unfocused)`."
  },
  {
    "name": "--infinite-row-hover-background",
    "label": "Hover background",
    "group": "Row",
    "kind": "color",
    "description": "Background color for rows, on hover.\n\nOverriden in the `dark` theme."
  },
  {
    "name": "--infinite-row-selected-hover-background",
    "label": "Selected hover background",
    "group": "Row",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-row-selected-disabled-background",
    "label": "Selected disabled background",
    "group": "Row",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-group-row-background",
    "label": "Group row background",
    "group": "Row",
    "kind": "color",
    "description": ""
  },
  {
    "name": "--infinite-group-row-column-nesting",
    "label": "Group row column nesting",
    "group": "Row",
    "kind": "text",
    "description": ""
  },
  {
    "name": "--infinite-row-pointer-events-while-scrolling",
    "label": "Pointer events while scrolling",
    "group": "Row",
    "kind": "text",
    "description": ""
  }
];
