name: 'Exec cmd'
description: 'Execute cmd in input'
branding:
  icon: upload-cloud
  color: green
  
inputs:
  cmd_to_execute:
    description: 'Command to execute'
    required: true

runs:
  using: 'node12'
  main: 'start.js'
