name: 'GitHub Push'
description: 'Pushing to GitHub repository local changes'

branding:
  icon: upload-cloud
  color: green
inputs:
  github_token:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
  repository:
    description: 'Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})'
    default: ''
    required: false
  branch:
    description: 'Destination branch to push changes'
    required: false
    default: 'master'
  force:
    description: 'Determines if force push is used'
    required: false
  directory:
    description: 'Directory to change to before pushing.'
    required: false
    default: '.'
  commit_message:
    required: false
    default: 'update'

runs:
  using: 'node20'
  main: 'start.js'
