export enum InfiniteTableActionType {
  SET_COLUMN_SIZE,
  // SET_VIEWPORT_SIZE,
  SET_SCROLL_POSITION,
  SET_BODY_SIZE,
  SET_COLUMN_ORDER,
  SET_COLUMN_VISIBILITY,
  SET_COLUMN_SHIFTS,
  SET_COLUMN_PINNING,
  SET_COLUMN_AGGREGATIONS,
  SET_DRAGGING_COLUMN_ID,
}
