name: Bundle Size

on:
  pull_request:
    paths:
      - 'source/src/**'
      - 'source/package.json'
      - 'source/tsup*.config.ts'

jobs:
  bundlewatch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            source/package-lock.json

      - name: Execute 'npm ci' in monorepo
        run: npm ci

      - name: Build package
        run: |
          npm run build

      - name: Run bundlewatch
        run: npm run bundlewatch
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
          CI_COMMIT_MESSAGE: ${{ github.event.pull_request.title }}
          CI_REPO_OWNER: ${{ github.repository_owner }}
          CI_REPO_NAME: 'infinite-table'
          CI_BRANCH: ${{ github.ref_name }}
          CI_COMMIT_SHA: ${{ github.sha }}
