name: Rebuild website

on:
  issues:
    types: [opened, edited, milestoned]
  label:
    types: [created, edited, deleted]
  workflow_run:
    # when the "RELEASE" workflow is completed successfully, we need to react and run this publish-docs workflow
    workflows: [RELEASE]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Building'
        run: |
          npm run build-website

      - name: checkout infinite-www-dist repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
          repository: infinite-table/infinite-www-dist
          path: infinite-www-dist

      - name: Replace old out folder with new one
        run: rm -fr ./infinite-www-dist/out && mv ./www/out ./infinite-www-dist
        shell: bash

      - uses: './.github/actions/git-commit-push-action'
        name: Push changes
        with:
          github_token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
          directory: infinite-www-dist
          repository: infinite-table/infinite-www-dist
          commit_message: ${{ github.event.head_commit.message }}
