name: Rebuild website

on:
  push:
    paths:
      - 'www/**'
  issues:
    types: [opened, edited, milestoned, closed]
  label:
    types: [created, edited, deleted]
  workflow_run:
    # when the "RELEASE" workflow is completed successfully, we need to react and run this workflow
    workflows: [RELEASE]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
      NEXT_PUBLIC_INFINITE_LICENSE_KEY: ${{ secrets.NEXT_PUBLIC_INFINITE_LICENSE_KEY }}
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Building'
        run: |
          npm run build-website

      - name: checkout infinite-www-dist repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
          repository: infinite-table/infinite-www-dist
          path: infinite-www-dist
          ref: ${{ github.ref_name}}

      - name: Copy netlify.toml
        run: cp ./netlify.toml ./infinite-www-dist

      - name: Replace old www folder with new one
        run: rm -fr ./infinite-www-dist/www && mv ./www ./infinite-www-dist

      - uses: './.github/actions/git-push-action'
        name: Push changes
        with:
          github_token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
          directory: infinite-www-dist
          repository: infinite-table/infinite-www-dist
          commit_message: ${{ github.event.head_commit.message }}
          branch: ${{github.ref_name}}
