name: Rebuild website

on:
  issues:
    types: [opened, edited, milestoned]
  label:
    types: [created, edited, deleted]
  workflow_run:
    # when the "RELEASE" workflow is completed successfully, we need to react and run this publish-docs workflow
    workflows: [RELEASE]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-netlify-hook:
    runs-on: ubuntu-latest

    steps:
      - name: Run netlify hook
        env:
          NETLIFY_HOOK: ${{ secrets.NETLIFY_REBUILD_WEBSITE_HOOK }}
        run: |
          curl -X POST -d {} ${NETLIFY_HOOK}
