name: Rebuild website

on:
  push:
    paths:
      - 'www/**'
    branches:
      - master
      - dev
  issues:
    types: [opened, edited, milestoned, closed]
  label:
    types: [created, edited, deleted]
  workflow_run:
    # when the "RELEASE" workflow is completed successfully, we need to react and run this workflow
    workflows: [RELEASE]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  publish-website:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
      NEXT_PUBLIC_INFINITE_LICENSE_KEY: ${{ secrets.NEXT_PUBLIC_INFINITE_LICENSE_KEY }}
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            source/package-lock.json
            www/package-lock.json
            examples/package-lock.json

      - name: Install
        run: npm ci --force

      - name: 'Building'
        run: |
          npm run build:all

      - name: checkout infinite-www-dist repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
          repository: infinite-table/infinite-www-dist
          path: infinite-www-dist
          ref: ${{ github.ref_name}}

      - name: Copy netlify.toml
        run: cp ./netlify.toml ./infinite-www-dist

      - name: Replace old www folder with new one
        run: rm -fr ./infinite-www-dist/www && mv ./www ./infinite-www-dist

      - uses: './.github/actions/git-push-action'
        name: Push changes
        with:
          github_token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
          directory: infinite-www-dist
          repository: infinite-table/infinite-www-dist
          commit_message: ${{ github.event.head_commit.message }}
          branch: ${{github.ref_name}}
