name: Rebuild website

on:
  issues:
    types: [opened, edited, milestoned]
  label:
    types: [created, edited, deleted]

jobs:
  run-netlify-hook:
    runs-on: ubuntu-latest

    steps:
      - name: Run netlify hook
        env:
          NETLIFY_HOOK: ${{ secrets.NETLIFY_REBUILD_WEBSITE_HOOK }}
        run: |
          curl -X POST -d {} ${NETLIFY_HOOK}
