name: Run ESBuild
on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BASE_URL: https://infinite-table.com/.netlify/functions/json-server

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "SHIP IT"

      - name: Install
        run: npm ci

      - name: Build test app
        run: npm run ci:test:build

      - name: Running Playwright Tests
        run: npm run ci:test:run

      - name: Update TOC in markdown files
        run: npm run doctoc

      - name: Bump version
        working-directory: source
        run: npm run bump:minor

      - name: Building
        run: npm run build
