name: Run ESBuild

on:
  push:
    branches:
      - master
    # paths-ignore:
    #   - 'www/**'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  release:
    if: ${{ contains(github.event.head_commit.message, 'release version') }}
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BASE_URL: https://infinite-table.com/.netlify/functions/json-server

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci

      - name: Building
        run: npm run build
