name: Test
on:
  push:
    paths:
      - 'source/src/**'

jobs:
  run-tests:
    env:
      NEXT_PUBLIC_BASE_URL: http://infinite-table.com/.netlify/functions/json-server
      NEXT_PUBLIC_BASE_URL_FOR_TESTS: http://infinite-table.com/.netlify/functions/json-server
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci --force && npm ci --force  --prefix source && npm ci --force  --prefix source/examples
      # - name: Linting
      #   run: npm run lint
      #   working-directory: source

      - name: Run test suite
        run: npm test
